Add files via upload
nstrydom2/anonfile-api pull request #70
Opened 2022-05-12 20:26 UTC by MobCat

Added a ParseResponse for the formatted file size string.

2022-05-21 01:38 UTC, hentai-chan requested changes
Small changes are required, but other than that the code looks good to me.

2022-05-21 01:38 UTC, hentai-chan commented on src/anonfile/anonfile.py
> +    # It was the only dedicated response missing from the original json query
You should remove this comment, put it in a commit message if you want to but don't add these remarks in the code directly.

2022-05-21 01:38 UTC, hentai-chan commented on src/anonfile/anonfile.py
> +    def sizeStr(self) -> str:
Method names in Python should always be written in snake_case.

2022-05-22 22:28 UTC, MobCat commented
Sorry for the late reply. I've never done a code push on github before. So if possible please make any changes you need to. I don't really know what I have to do on my end.

2022-05-24 23:37 UTC, hentai-chan commented
You just need to make a new commit on the repository where this pull request stems from.

2022-11-04 22:50 UTC, hentai-chan commented
@MobCat Hey ya, just chiming in to check if you are still working on this PR? If not I can add the due changes myself in the coming days, so your work isn't lost. I will leave this up during the weekend and come back on Monday to see if this branch is still stale, else I will consider it up for grabs :)

2023-07-14 20:55 UTC, StefanGreve commented
Closed by #80

2023-07-14 20:55 UTC, closed without merging